stages:
  - build
  - deploy-dev
  - deploy-prod

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

build-server:
  stage: build
  image: docker:25.0.5
  services:
    - docker:25.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f server/Dockerfile -t $CI_REGISTRY_IMAGE/server-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE/server-$CI_COMMIT_REF_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE/server-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/server-$CI_COMMIT_REF_NAME:latest
  only:
    - main
    - dev

build-client:
  stage: build
  image: docker:25.0.5
  services:
    - docker:25.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f client/Dockerfile -t $CI_REGISTRY_IMAGE/client-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE/client-$CI_COMMIT_REF_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE/client-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/client-$CI_COMMIT_REF_NAME:latest
  only:
    - main
    - dev