version: '3.8'

services:
  client:
    image: $CI_REGISTRY_IMAGE/client:latest
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  server:
    image: $CI_REGISTRY_IMAGE/server:latest
    expose:
      - "3000"
    environment:
      - NODE_ENV=production