{{- $password := randAlphaNum 32 }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
  uri: {{ printf "mongodb://admin:%s@mongodb-service:27017/clubhive?authSource=admin" $password | b64enc | quote }}