name: Build and Push

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

env:
  NODE_VERSION: "22"
  DOCKER_IMAGE_SERVER: clubhive/server
  DOCKER_IMAGE_CLIENT: clubhive/client

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            server/node_modules
            shared/node_modules
          key: server-${{ hashFiles('server/package-lock.json', 'shared/package-lock.json') }}
          restore-keys: |
            server-

      - name: Install shared dependencies
        run: cd shared && npm ci

      - name: Install server dependencies
        run: cd server && npm ci --ignore-scripts

      - name: Build server
        run: cd server && npm run build

  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            client/node_modules
            shared/node_modules
          key: client-${{ hashFiles('client/package-lock.json', 'shared/package-lock.json') }}
          restore-keys: |
            client-

      - name: Install shared dependencies
        run: cd shared && npm ci

      - name: Install client dependencies
        run: cd client && npm ci --ignore-scripts

      - name: Build client
        run: cd client && npm run build

  docker-build-server:
    name: Docker Build Server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.DOCKER_IMAGE_SERVER }}-${{ steps.extract_branch.outputs.branch }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE_SERVER }}-${{ steps.extract_branch.outputs.branch }}:latest

  docker-build-client:
    name: Docker Build Client
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: client/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.DOCKER_IMAGE_CLIENT }}-${{ steps.extract_branch.outputs.branch }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE_CLIENT }}-${{ steps.extract_branch.outputs.branch }}:latest
